_BASE_: "./Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
    NUM_CLASSES: 2
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.001
  WARMUP_ITERS: 1000
  STEPS: (210000, 250000)
  MAX_ITER: 100
  GAMMA: 0.052
DATASETS:
  TRAIN: ("midjourney_fog",)
  TEST: ("midjourney_fog",)
DATALOADER:
  NUM_WORKERS: 4
TEST:
  EVAL_PERIOD: 500